TIMEZONES = {
    "ET": "Eastern Standard Time",
    "CT": "Central Standard Time",
    "MT": "Mountain Standard Time",
    "PT": "Pacific Standard Time",
    "AK": "Alaskan Standard Time",
    "HAST": "Hawaiian Standard Time",
    "MST": "Mountain Standard Time",
    "AST": "Atlantic Standard Time",
    "MOST": "Morocco Standard Time",
    "UTC": "UTC",
    "GMT": "GMT Standard Time",
    "GST": "Greenwich Standard Time",
    "WET": "West Europe Standard Time",
    "CET": "Central Europe Standard Time",
    "RST": "Romance Standard Time",
    "CEST": "Central European Standard Time",
    "ECT": "W. Central Africa Standard Time",
    "JST": "Japan Standard Time",
    "GTBST": "GTB Standard Time",
    "MEST": "Middle East Standard Time",
    "EGST": "Egypt Standard Time",
    "SST": "Syria Standard Time",
    "SAST": "South Africa Standard Time",
    "EET": "FLE Standard Time",
    "ISST": "Israel Standard Time",
    "EEST": "E. Europe Standard Time",
    "NMST": "Namibia Standard Time",
    "ARST": "Arabic Standard Time",
    "ABST": "Arab Standard Time",
    "MSK": "Russian Standard Time",
    "EAT": "E. Africa Standard Time",
    "IRST": "Iran Standard Time",
    "ARBST": "Arabian Standard Time",
    "AZT": "Azerbaijan Standard Time",
    "MUT": "Mauritius Standard Time",
    "GET": "Georgian Standard Time",
    "AMT": "Caucasus Standard Time",
    "AFT": "Afghanistan Standard Time",
    "YEKT": "Ekaterinburg Standard Time",
    "PKT": "Pakistan Standard Time",
    "WAST": "West Asia Standard Time",
    "IST": "India Standard Time",
    "SLT": "Sri Lanka Standard Time",
    "NPT": "Nepal Standard Time",
    "BTT": "Central Asia Standard Time",
    "BST": "Bangladesh Standard Time",
    "NCAST": "N. Central Asia Standard Time",
    "MYST": "Myanmar Standard Time",
    "THA": "SE Asia Standard Time",
    "KRAT": "North Asia Standard Time",
    "IRKT": "North Asia East Standard Time",
    "SNST": "Singapore Standard Time",
    "AWST": "W. Australia Standard Time",
    "TIST": "Taipei Standard Time",
    "UST": "Ulaanbaatar Standard Time",
    "TST": "Tokyo Standard Time",
    "KST": "Korea Standard Time",
    "YAKT": "Yakutsk Standard Time",
    "CAUST": "Cen. Australia Standard Time",
    "ACST": "AUS Central Standard Time",
    "EAST": "E. Australia Standard Time",
    "AEST": "AUS Eastern Standard Time",
    "WPST": "West Pacific Standard Time",
    "TAST": "Tasmania Standard Time",
    "VLAT": "Vladivostok Standard Time",
    "SBT": "Central Pacific Standard Time",
    "NZST": "New Zealand Standard Time",
    "UTC12": "UTC+12",
    "FJT": "Fiji Standard Time",
    "PETT": "Kamchatka Standard Time",
    "PHOT": "Tonga Standard Time",
    "AZOST": "Azores Standard Time",
    "CVT": "Cape Verde Standard Time",
    "ESAST": "E. South America Standard Time",
    "ART": "Argentina Standard Time",
    "SAEST": "SA Eastern Standard Time",
    "GNST": "Greenland Standard Time",
    "MVST": "Montevideo Standard Time",
    "NST": "Newfoundland Standard Time",
    "PRST": "Paraguay Standard Time",
    "CBST": "Central Brazilian Standard Time",
    "SAWST": "SA Western Standard Time",
    "PSAST": "Pacific SA Standard Time",
    "VST": "Venezuela Standard Time",
    "SAPST": "SA Pacific Standard Time",
    "EST": "US Eastern Standard Time",
    "CAST": "Central America Standard Time",
    "CST": "Central Standard Time (Mexico)",
    "CCST": "Canada Central Standard Time",
    "MSTM": "Mountain Standard Time (Mexico)",
    "PST": "Pacific Standard Time (Mexico)",
    "SMST": "Samoa Standard Time",
    "BIT": "Dateline Standard Time",
}
